### ISSUE TITLE
Update core?

### ISSUE THREAD

**Issue by OmgImAlexis** [fleXible/ha-ps4-custom#1]
I recently added my PS4 and I think I'm also hitting this issue. Is there a reason this hasn't been added as a PR to the core repo? Just wanted to check before trying it out.

**Comment by fleXible** [comment]
It's complicated :) We tried to get the code into home assistant, but after serveral tries we had to give up.

**Comment by OmgImAlexis** [comment]
> It's complicated :) We tried to get the code into home assistant, but after serveral tries we had to give up.

Is there a PR or issue I can checkout?

**Comment by fleXible** [comment]
Yes, check this out: home-assistant/architecture/discussions/504
